export const constantsOfActions = {
    setUser: 'setUser',
    invalidEmail: 'invalidEmail',
    occupiedEmail: 'occupiedEmail',
    occupiedUsername: 'occupiedUsername',
    incorrectPassword: 'incorrectPassword',
    moveToSignUp: 'moveToSignUp',
    moveToLogin: 'moveToLogin',
    moveToProfile: 'moveToProfile',
    moveToContacts: 'moveToContacts',
    moveToChats: 'moveToChats',
    moveToChat: 'moveToChat',
    moveToCreateGroup: 'moveToCreateGroup',
    moveToCreateChannel: 'moveToCreateChannel',
    moveToEditChat: 'moveToEditChat',
    deleteState: 'deleteState',
    render: 'render',
    setContacts: 'setContacts',
    addChat: 'addChat',
    openChat: 'openChat',
    setChats: 'setChats',
    createGroup: 'createGroup',
    deleteChat: 'deleteChat',
    editChat: 'editChat',
    isNotRendered: 'isNotRendered',
}
