export const constantsOfActions = {
    setUser: 'setUser',
    invalidEmail: 'invalidEmail',
    occupiedEmail: 'occupiedEmail',
    occupiedUsername: 'occupiedUsername',
    moveToSignUp: 'moveToSignUp',
    moveToLogin: 'moveToLogin',
    moveToProfile: 'moveToProfile',
    moveToContacts: 'moveToContacts',
    moveToChats: 'moveToChats',
    moveToCreateGroup: 'moveToCreateGroup',
    deleteState: 'deleteState',
    render: 'render',
    setContacts: 'setContacts',
    addChat: 'addChat',
    openChat: 'openChat',
    setChats: 'setChats',
    createGroup: 'createGroup',
    sendMessage: 'sendMessage',
    deleteChat: 'deleteChat',
    deleteGroup: 'deleteGroup',
    deleteChannel: 'deleteChannel',
}
